# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
url:              http://lucasgruwez.github.io
baseurl:          /waffle-grid
encoding:         UTF-8

# Custom vars
version:          v1.2.1
repo:             https://github.com/lucasgruwez/waffle-grid
download:         https://github.com/lucasgruwez/waffle-grid/releases/download/v1.2.1/waffle-grid.min.css
cdn:              https://unpkg.com/waffle-grid@1.2.1
docs:             https://github.com/lucasgruwez/waffle-grid/wiki
