# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
url:              http://lucasgruwez.github.io/waffle-grid
encoding:         UTF-8

# Custom vars
current_version:  1.0.0
repo:             https://github.com/lucasgruwez/waffle-grid

download:         https://github.com/lucasgruwez/waffle-grid/releases/download/v1.0.0/waffle-grid.min.css
